routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController as IndexController;
use App\Http\Controllers\SearchController as SearchController;
use App\Http\Controllers\ArticleController as ArticleController;
use App\Http\Controllers\Catalog\CatalogController as CatalogController;
use App\Http\Controllers\Catalog\ComplexController as ComplexController;
use App\Http\Controllers\Catalog\PenthouseController as PenthouseController;
use App\Http\Controllers\Forms\FormController as FormController;
use App\Http\Middleware\VerifyCsrfToken as VerifyCsrfToken;
use App\Http\Controllers\Catalog\PdfController as PdfController;

Auth::routes();

Route::get('/', [IndexController::class, 'index'])->name('index');

Route::get('/article', [ArticleController::class, 'index'])->name('article');

Route::prefix('catalog')->name('catalog')->group(function (){
    Route::get('/', [CatalogController::class, 'index']);
    Route::post('/filterAjax', [CatalogController::class,'filterAjax'])->withoutMiddleware([VerifyCsrfToken::class])->name('.filter.ajax');
    Route::get('/{complex}', [ComplexController::class, 'index'])->name('.complex');
    Route::get('/{complex}/{penthouse}', [PenthouseController::class, 'index'])->name('.penthouse');
});

Route::post('/feedback', [FormController::class,'feedback'])->name('forms.feedback');
Route::get('/search', [SearchController::class, 'index'])->name('search');

Route::prefix('pdf')->name('pdf')->group(function (){
    Route::get('/', [PdfController::class, 'index']);
    Route::get('/{complex}', [PdfController::class, 'complex'])->name('.complex');
    Route::get('/{complex}/{penthouse}', [PdfController::class, 'penthouse'])->name('.penthouse');
});

Route::get('/image', [PdfController::class, 'image'])->name('image');

app/Models/Catalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Catalog extends Model
{
    use HasFactory;

    public function link(): string
    {
        return $link = 'catalog';
    }

    public function getTagName(): \Illuminate\Database\Eloquent\Builder
    {
        return Tag::query()->select('tag_name');
    }
    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

    public function complexCount(): \Illuminate\Database\Eloquent\Builder
    {
        return Complex::query()->join('complex_location', 'complex_location.complex_id', '=', 'complexes.id')
            ->join('locations','complex_location.location_id', '=', 'locations.id')
            ->select('complexes.id','complex_title','locations.location')
            ->withCount('penthouses');
    }

    public function getPenthouses(): \Illuminate\Database\Eloquent\Builder
    {
        return Penthouse::query()->with('apartment')
            ->join('complexes', 'complexes.id', '=', 'penthouses.complex_id')
            ->join('complex_location', 'complex_location.complex_id', '=', 'complexes.id')
            ->join('locations','complex_location.location_id', '=', 'locations.id')
            ->select('penthouses.id', 'penthouse_slug', 'penthouse_title', 'full_price_ru', 'square', 'rooms', 'terrace',
                'square_terrace', 'penthouse_main_img', 'penthouse_img', 'penthouses.complex_id','complexes.id as complexes_id',
                'complex_slug', 'complex_title', 'complex_desc', 'complex_address', 'delivery', 'infrastructure',
                'complex_main_img', 'complex_img', 'locations.location as location');
    }
}

app/Http/Controllers/Catalog/CatalogController.php
<?php

namespace App\Http\Controllers\Catalog;

use App\Http\Controllers\Controller;
use App\Models\Catalog;
use App\Http\Filters\CatalogFilter;
use Illuminate\Http\Request;

class CatalogController extends Controller
{
    public function index(Catalog $catalogModel, CatalogFilter $filters, Request $request)
    {
        $link = $catalogModel->link();
        $tags = $catalogModel->getTagName()->get();
        $complexes = $catalogModel->complexCount()->get();
        $penthouses = $catalogModel->getPenthouses()->filter($filters)->paginate(6);

        return view('catalog.catalog', compact('link', 'penthouses', 'tags', 'complexes', 'request'));
    }
}

app/Http/Controllers/Catalog/ComplexController.php
<?php

namespace App\Http\Controllers\Catalog;

use App\Http\Controllers\Controller;
use App\Http\Filters\PenthouseFilter;
use App\Models\Complex;
use Illuminate\Http\Request;

class ComplexController extends Controller
{
    public function index(Complex $complexModel, PenthouseFilter $filters, Request $request, $complex_slug)
    {
        $link = $complexModel->link();
        $complex = $complexModel->getComplex($complex_slug)->firstOrFail();
        $pents = $complexModel->getComplexPent($complex->id)->filter($filters)->get();

        return view('catalog.complex', compact('link', 'complex', 'pents', 'request'));
    }
}

app/Http/Controllers/Catalog/PdfController.php
<?php

namespace App\Http\Controllers\Catalog;

use App\Http\Controllers\Controller;
use App\Models\Complex;
use App\Models\Index;
use App\Models\Penthouse;
use PDF;
use Image;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class PdfController extends Controller
{
    public function index(Index $indexModel)
    {
//        ->generate('http://pent.nextbrand.ru/catalog/'. $complex_slug .'/'. $penthouse_slug .'')
        $qrCodeC = QrCode::encoding('UTF-8')->size(193);
        $qrCodeP = QrCode::encoding('UTF-8')->size(193);
        $complex = $indexModel->getComplex()->get();
        $data = [
            'qrCodeP' => $qrCodeP,
            'qrCodeC' => $qrCodeC,
            'complex' => $complex
        ];

        $pdf = PDF::loadView('pdf.pdf-index', compact('data'));
        return $pdf->stream('pdf-index.pdf');
    }

    public function complex(Complex $complexModel, $complex_slug)
    {
        $qrCode = QrCode::encoding('UTF-8')->size(193)->generate('http://pent.nextbrand.ru/catalog/'. $complex_slug .'');
        $complex = $complexModel->getComplex($complex_slug)->firstOrFail();
        $pents = $complexModel->getComplexPent($complex->id)->get();

        $data = [
            'qrCode' => $qrCode,
            'complex' => $complex,
            'pents' => $pents,
        ];

        $pdf = PDF::loadView('pdf.pdf-complex', compact('data'));
        return $pdf->stream('pdf-complex.pdf');
    }

    public function penthouse(Complex $complexModel, Penthouse $penthouseModel, $complex_slug, $penthouse_slug)
    {
        $qrCodeC = QrCode::encoding('UTF-8')->size(193)->generate('http://pent.nextbrand.ru/catalog/'. $complex_slug .'');
        $qrCodeP = QrCode::encoding('UTF-8')->size(193)->generate('http://pent.nextbrand.ru/catalog/'. $complex_slug .'/'. $penthouse_slug .'');
        $penthouse = $penthouseModel->getPenthouse($complex_slug, $penthouse_slug)->firstOrFail();
        $pents = $complexModel->getComplexPent($penthouse->complex->id)->get();

        $data = [
            'qrCodeP' => $qrCodeP,
            'qrCodeC' => $qrCodeC,
            'penthouse' => $penthouse,
            'pents' => $pents
        ];

        $pdf = PDF::loadView('pdf.pdf-penthouse', compact('data'));
        return $pdf->stream('pdf-penthouse.pdf');
    }

    public function image()
    {
        $img = Image::make(public_path('/images/barkli/barkli-1-tel.png'))->resize(300, 200);
        return $img->response('jpg');
    }
}

app/Http/Controllers/Catalog/PenthouseController.php
<?php

namespace App\Http\Controllers\Catalog;

use App\Http\Controllers\Controller;
use App\Http\Filters\PenthouseFilter;
use App\Models\Penthouse;
use Illuminate\Http\Request;

class PenthouseController extends Controller
{
    public function index(Penthouse $penthouseModel, PenthouseFilter $filters, Request $request, $complex_slug, $penthouse_slug)
    {
        $link = $penthouseModel->link();
        $penthouse = $penthouseModel->getPenthouse($complex_slug, $penthouse_slug)->firstOrFail();
        $pentComplex = $penthouseModel->getPentComplex($complex_slug)->filter($filters)->get();

        return view('catalog.penthouse', compact(  'link','penthouse','pentComplex', 'request'));
    }
}

resources/views/catalog/complex.blade.php
@extends('layouts.layout-2')
@section('page-title', $complex->complex_title)
@section('breadcrumbs', Breadcrumbs::render('catalog.complex', $complex))

@section('content')

    <div class="gallery">
        <h1 class="gallery__title main-title">{{$complex->complex_title}}</h1>
        <div class="gallery__list swiper-container">
            <button class="swiper-button-prev"></button>
            <button class="swiper-button-next"></button>
            <div class="swiper-wrapper">
            @foreach($complex->complex_img as $com_img)
                <a href="#" class="gallery__item swiper-slide">
                    <div class="gallery__img-tel">
                        <img src="{{ asset($complex->fit($com_img, 306, 124)) }}" alt='ЖК "БАРКЛИ ГАЛЕРИ"'>
                    </div>
                    <div class="gallery__img-dekstop">
                        <img src="{{ asset($complex->fit($com_img, 1205, 677)) }}" alt='ЖК "БАРКЛИ ГАЛЕРИ"'>
                    </div>
                </a>
            @endforeach
            </div>
        </div>
    </div>

    <div class="barkli">
        <aside class="order">
            <div class="order__show">
                <p class="order__address">{{$complex->complex_address}}</p>
                <a class="order__link" href="#">Показать на карте</a>
            </div>
            <div class="order__info">
                <a class="order__inspection form-toggle" href="#">Заказать осмотр</a>
                <ul class="order__list">
                    <li class="order__item">
                        <span class="order__class">Класс</span>
                        <span class="order__type">{{ $complex->class }}</span>
                    </li>
                    <li class="order__item">
                        <span class="order__class">Готовность</span>
                        <span class="order__type">{{$complex->delivery}}</span>
                    </li>
                    <li class="order__item">
                        <span class="order__class">Инфраструктура</span>
                        <span class="order__type">{{$complex->infrastructure}}</span>
                    </li>
                    <li class="order__item">
                        <span class="order__class">Класс</span>
                        <span class="order__type">{{ $complex->class }}</span>
                    </li>
                    <li class="order__item">
                        <span class="order__class">Готовность</span>
                        <span class="order__type">{{$complex->delivery}}</span>
                    </li>
                    <li class="order__item">
                        <span class="order__class">Инфраструктура</span>
                        <span class="order__type">{{$complex->infrastructure}}</span>
                    </li>
                </ul>
            </div>
        </aside>
        <div class="mansion__page barkli__page">
            <section class="barkli__info">
                <h2 class="visually-hidden">Информация о {{$complex->complex_title}}"</h2>
                <p class="barkli__text">{{$complex->complex_desc}}</p>
            </section>
            <h2 class="barkli__title sec-title">Пентхаусы в {{$complex->complex_title}}</h2>
            <header class="mansion__header">
                <div class="mansion__sort">
                    <p class="mansion__sort-num">Пентхаусов найдено: <span>{{$complex->penthouses_count}}</span></p>
                    <p class="mansion__sort-type">Сортировать по:
                    @if($request->price == 'asc')
                        <a class="mansion__sort-type__btn" href="{{ $request->fullUrlWithQuery(['price' => 'desc']) }}">Цене, сначала дорогие</a>
                    @else
                        <a class="mansion__sort-type__btn" href="{{ $request->fullUrlWithQuery(['price' => 'asc']) }}">Цене, сначала дешевле</a>
                    @endif
                    </p>
                </div>
            </header>
            <ul class="mansion__kind">
            @foreach($pents as $penthouse)
                @foreach($penthouse->tags as $tag)
                    <li class="flat__kind-item"><a class="mansion__kind-btn" href="#">{{ $tag->tag_name }}</a></li>
                @endforeach
            @endforeach
            </ul>
            <div class="mansion__house-wrapper">
            @foreach($pents as $penthouse)
                <div class="mansion__house barkli__house">
                    <div class="mansion__img">
                        <img src="{{ asset($penthouse->fit($penthouse->penthouse_main_img, 600, 428)) }}" alt="пентхаус">
                    </div>
                    <div class="mansion__info">
                        <div class="mansion__info-top">
                            <h2 class="mansion__title">{{ $penthouse->penthouse_title }}</h2>
                            <p class="mansion__street">{{ $complex->complex_address }}</p>
                            <ul class="mansion__content">
                                <li>{{ $penthouse->rooms }} <span>спальни</span></li>
                                <li>Отделка <span>{{ $penthouse->apartment }}</span></li>
                            </ul>
                            <ul class="mansion__features">
                                @foreach($penthouse->tags as $tag)
                                    <li>{{ $tag->tag_name }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <div class="mansion__info-bottom">
                            <p class="mansion__size">{{ $penthouse->square }} м<sup>2</sup>
                                @if($penthouse->terrace == true)
                                    + терраса {{ $penthouse->square_terrace }} м<sup>2</sup></p>
                                @endif
                            <p class="mansion__price">{{ $penthouse->full_price_ru }} &#8381;</p>
                            <div class="mansion__info-about">
                                <p class="mansion__metre">328 000 р./м<sup>2</sup></p>
                                <div class="mansion__more"><a href="{{ route('catalog.penthouse',[$complex->complex_slug, $penthouse->penthouse_slug]) }}">Подробнее</a></div>
                            </div>
                        </div>
                        <a class="mansion__link" href="{{ route('catalog.penthouse',[$complex->complex_slug, $penthouse->penthouse_slug]) }}">Назначить осмотр</a>
                    </div>
                </div>
            @endforeach
            </div>
            <div class="mansion__map" id="map">
            </div>
        </div>
    </div>

    <section class="house sec barkli-house">
        <div class="house__inner">
            <header class="house__header">
                <h2 class="house__chapter">Вам понравятся эти пентхаусы</h2>
                <a class="house__all" href="#">Показать все предложения</a>
            </header>
            <div class="house__list swiper-container">
                <button class="swiper-button-prev"></button>
                <button class="swiper-button-next"></button>
                <div class="swiper-wrapper">
                    <a class="house__item swiper-slide" href="#">
                        <div class="house__img">
                            <img src="{{ asset('images/fireplace/fireplace-1.png') }}" alt="fireplace-1" width="208" height="165">
                        </div>
                        <div class="house__info">
                            <h3 class="house__title">Пентхаус в ЖК <br> "ГРАН ПРИ"</h3>
                            <div class="house__about">
                                <p class="house__area">665 м<sup>2</sup> + терраса 60 м<sup>2</sup></p>
                                <p class="house__price">648 000 000 &#8381;</p>
                            </div>
                        </div>
                    </a>
                    <a class="house__item swiper-slide" href="#">
                        <div class="house__img">
                            <img src="{{ asset('images/fireplace/fireplace-2.png') }}" alt="fireplace-2" width="208" height="165">
                        </div>
                        <div class="house__info">
                            <h3 class="house__title">Пентхаус ЖК <br> "АНДРЕЕВСКИЙ"</h3>
                            <div class="house__about">
                                <p class="house__area">85 м<sup>2</sup> + терраса 90 м<sup>2</sup></p>
                                <p class="house__price">675 000 000 &#8381;</p>
                            </div>
                        </div>
                    </a>
                    <a class="house__item swiper-slide" href="#">
                        <div class="house__img">
                            <img src="{{ asset('images/fireplace/fireplace-3.png') }}" alt="fireplace-3" width="208" height="165">
                        </div>
                        <div class="house__info">
                            <h3 class="house__title">Пентхаус В ЖК <br> "ДОМ СО ЛЬВАМИ"</h3>
                            <div class="house__about">
                                <p class="house__area">165 м<sup>2</sup> + терраса 120 м<sup>2</sup></p>
                                <p class="house__price">90 000 000 &#8381;</p>
                            </div>
                        </div>
                    </a>
                    <a class="house__item swiper-slide" href="#">
                        <div class="house__img">
                            <img src="{{ asset('images/fireplace/fireplace-4.png') }}" alt="fireplace-4" width="208" height="165">
                        </div>
                        <div class="house__info">
                            <h3 class="house__title">Пентхаус В ЖК <br> "BOLSHEVIK"</h3>
                            <div class="house__about">
                                <p class="house__area">112 м<sup>2</sup> + терраса 40 м<sup>2</sup></p>
                                <p class="house__price">874 000 000 &#8381;</p>
                            </div>
                        </div>
                    </a>
                    <a class="house__item swiper-slide" href="#">
                        <div class="house__img">
                            <img src="{{ asset('images/fireplace/fireplace-5.png') }}" alt="fireplace-5" width="208" height="165">
                        </div>
                        <div class="house__info">
                            <h3 class="house__title">Пентхаус В ЖК <br> "КУТУЗОВСКИЙ, 12"</h3>
                            <div class="house__about">
                                <p class="house__area">450 м<sup>2</sup> + терраса 10 м<sup>2</sup></p>
                                <p class="house__price">761 000 000 &#8381;</p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    @include('layouts.modules.catalog')

    @include('layouts.modules.features')

@endsection